### ISSUE TITLE
Parameter autocompletion works until a call symbol match

### ISSUE THREAD

**Issue by strboul** [REditorSupport/languageserver#288] opened 2020-06-28 11:04 UTC
Relates #285

I don't know if this is a desired behavior but it looks a bit odd to me.

![video](https://user-images.githubusercontent.com/25015317/85945687-cbb5f800-b93f-11ea-865c-00a855e9f5fc.gif)

**Comment by renkun-ken** [comment] 2020-06-28 11:46
It looks like an exact match always ranks higher than others?

**Comment by renkun-ken** [comment] 2020-06-28 14:37
I could reproduce this in VSCode. However, I'm not if we can do anything about it.

**Comment by strboul** [comment] 2020-06-28 21:28
Just to note: call parameters in the RStudio's autocompletion precede the exact matches so this behavior might be the one for better usability.

<img width="475" alt="rs" src="https://user-images.githubusercontent.com/25015317/85958344-2d548180-b995-11ea-90ea-dedbac9978b8.png">

**Comment by renkun-ken** [comment] 2020-07-02 08:15
It looks like we can do nothing about it at the moment. Closing now.

**Closed by renkun-ken** 2020-07-02 08:15 UTC
