### ISSUE TITLE
incorrectly returns an array of strings for `newText`

### ISSUE THREAD

**Issue by siegel** [REditorSupport/languageserver#414] opened 2021-04-10 14:31 UTC
I'm working on a new LSP client, and I've found a case in which the R language server appears to incorrectly return an array of strings rather than a single string for an element in a `textEdits` array. This is in response to a `textDocument/formatting` request.

A representative `textEdit` response showing the malformation looks like this:

```
{
    newText =     (
        "source(\"~/R/kernel_enrichment.r\")",
        "",
        " robust_z_scale <- function(x, min=NULL, minQ=NULL, by=\"row\") {",
        "        direction <- if_else(by == \"row\", 1, 2)",
        "        means <- apply(x, direction, mean, na.rm=TRUE)",
        "        y <- sweep(x, direction, means, \"-\")",
        "        sds <- apply(y, direction, sd, na.rm=TRUE)",
        "        if (!is.null(min)) { sds <- truncRange(sds, low=min) }",
        "        else if (!is.null(minQ)) {",
        "                min <- quantile(sds[sds > 0], minQ, na.rm=T)",
        "                sds <- truncRange(sds, low=min)",
        "        }",
        "        z <- sweep(y, direction, sds, \"/\")",
        "        z",
        "}",
        "",
        ""
    );
    range =     {
        end =         {
            character = 0;
            line = 75;
        };
        start =         {
            character = 0;
            line = 14;
        };
    };
}
```

Unfortunately, the R language server appears to only do this *some* of the time; I have not yet figured out what triggers it. (Unfortunately I am unable to provide the entire file in question; it is customer data.)

However, since the specification unambiguously states that the `newText` of a `textEdit` element is a string, and does not state any other allowable formats,  I think that the language server should only ever return a string, and never an array.

Thanks for reading; please let me know if there's any more information I can provide.

**Comment by renkun-ken** [comment] 2021-04-10 15:15
Is this produced in a formatting provider? Do you have a consistent way or example to cause this?

**Comment by randy3k** [comment] 2021-04-10 16:06
it does look like the formatting provider.

**Comment by siegel** [comment] 2021-04-10 16:23
Correct — it's the formatting provider and I apologize for not mentioning this in the initial report.

I will check with the customer and get their permission to post the file that I used to reproduce the symptom.

**Comment by randy3k** [comment] 2021-04-10 16:47
Do you know weather it is `textDocument/formatting` or `textDocument/rangeFormatting`?

**Comment by siegel** [comment] 2021-04-10 16:50
This is in response to a `textDocument/formatting` request.

**Comment by siegel** [comment] 2021-04-13 18:32
Here's an example file supplied by the customer which reproduces the reported behavior.
[test4.Rmd.zip](https://github.com/REditorSupport/languageserver/files/6305918/test4.Rmd.zip)

**Comment by renkun-ken** [comment] 2021-04-14 03:35
@siegel Could you try the latest development version of  languageserver and latest CRAN release of styler? I cannot reproduce the error with these.

```r
remotes::install_github("REditorSupport/languageserver")
install.packages("styler")
```

**Comment by siegel** [comment] 2021-05-01 14:16
With apologies for the delay: I have re-tested after installing updates as described, and see the same output as in my initial report.

**Comment by renkun-ken** [comment] 2021-06-26 03:31
I still cannot reproduce the problem with R 4.1 on macOS. Would you post your environment?

**Comment by siegel** [comment] 2021-06-28 18:40
After updating to 4.1 and reinstalling `styler`, I'm seeing the expected data returned from the `textDocument/formatting` request. I appreciate the fix, insofar as there appears to have been one. :-)

**Comment by renkun-ken** [comment] 2021-06-28 22:02
Closing as not reproducible. Feel free to open if you could reproduce it with the latest version of packages.

**Closed by renkun-ken** 2021-06-28 22:02 UTC
