### ISSUE TITLE
language server uses excessive CPU

### ISSUE THREAD

**Issue by atanasj** [REditorSupport/languageserver#245] opened 2020-04-25 12:06 UTC
CPU usage seems excessive when using `languageserver`. I've tested in both `emacs` and `vscode` and CPU usage creeps up to 90+%. This makes the experience slow and saving files takes some time. I'm not sure what other information to provide you apart from the below:

```bash
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G3020

R version 3.6.3 (2020-02-29) -- "Holding the Windsock"

languageserver 0.3.5 (from github)

GNU Emacs 28.0.50

vscode 1.44.2
```

Please let me know if you need any more info.

**Comment by renkun-ken** [comment] 2020-04-25 14:25
Thanks for reporting.

I'm using VSCode on both Ubuntu Server and macOS but do not observe such constant high CPU usage. Would you like to elaborate on your case by sharing the answers to the following questions:

1. Does your CPU usage go high whenever the languageserver is started or does it only occur after you do something like save or format or something?

2. How many CPU threads do you have? The current implementation of async task manager is quite aggressive and the loading could be heavy for machines with only a few CPU cores (i.e. less than 4).

3. Are you editing a large script (thousand of lines of code)? Working with large script could be stressful for many machines.

Currently, there are numerous language server providers that work on the basis of each document modification (including a number of edits in a short time). You may take a look at https://github.com/REditorSupport/languageserver#customizing-server-capbabilities and disable some LSP capabilities and see if the performance gets better. For example, you may edit your `~/.Rprofile` and disable some providers:

```r
options(
    languageserver.server_capabilities = list(
        documentOnTypeFormattingProvider = FALSE,
        documentLinkProvider = FALSE,
        colorProvider = FALSE
    )
)
```

In the future, we may refine the async task manager so that only a limited number of processes could be running at the same time to reduce overall CPU usage on machine.

**Comment by atanasj** [comment] 2020-04-26 02:31
> Does your CPU usage go high whenever the languageserver is started or does it only occur after you do something like save or format or something?

Usually when I just start it spikes but when I save it freezes from seconds until the document finally saves and I am able to type again.

> How many CPU threads do you have? The current implementation of async task manager is quite aggressive and the loading could be heavy for machines with only a few CPU cores (i.e. less than 4).

I have 4.

> Are you editing a large script (thousand of lines of code)? Working with large script could be stressful for many machines.

Nope. I just tested with the settings you suggested on a 300 line script (mostly comments).

I set the options you recommended, however it sill lags, freezes and sputters. I was watching my `HTOP` and language server CPU has decreased, however there seem to be multiple `R` processes running (see below). I am testing this in `Emacs`. When I kill the [`lsp-mode`](https://github.com/emacs-lsp/lsp-mode) which uses `languageserver` CPU usage issues is resolved.

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/27214625/80295840-7f243400-87b9-11ea-887f-057edfa90529.png">

Any ideas? Let me know if you need more info.

**Comment by renkun-ken** [comment] 2020-04-26 03:44
Looks like it is partially caused by format on save. In VSCode, `editor.formatOnSave` is on by default. Since we use `styler` to format R code, and its performance is far from ideal at the moment, I suggest that you disable formatOnSave for R with the following settings:

```json
"[r]": {
  "editor.formatOnSave": false
}
```

This disables formatOnSave specifically for R documents and does not affect other programming languages.

For the high CPU usage, it looks like it is caused by that the current task manager allows too many processes to run in parallel on your machine. We have multiple task managers (diagnostics, parse, resolve), diagnostics and parse run in parallel, resolve only runs after parse, but each is able to create multiple processes on demand. @randy3k, do you think the task managers could create too many processes when user is editing only one document? I see the implementation of task managers uses a kill and add method, which should not start too many processes for a single document.

**Comment by randy3k** [comment] 2020-04-26 04:12
I am trying to understand the screenshots. Did the other `R` processes come and go? Or do they persist?

**Comment by renkun-ken** [comment] 2020-04-26 05:03
From the current implementation of task manager, it could only create at most 3 processes for one document (diagnostics, parse -> resolve) and only at most two are running in parallel. This is consistent with my observation using `htop` filtered with `bin/exec/R` on my macbook.

Creating too many processes should only happen when user opens a workspace that is an R package and contains many R files.

**Comment by atanasj** [comment] 2020-04-26 12:07
@randy3k, the other processes come and go. However, they appear when completion options are being presented whilst I type. I tested in this in both `Emacs` and `VSCode` and I get the same additional processes (however, it is even slower and lags more in `Emacs`). 

@renkun-ken, I followed all of your suggestions but this issue still persists and has a performance impact. 

The impact / performance seems to be worse in `Emacs`.  I did some more debugging, and the three processes that appear when using `languageserver` are (image when using VSCode):

<img width="1275" alt="lsp_dual_proc_vsc_3tasks" src="https://user-images.githubusercontent.com/27214625/80306935-76f3e500-8809-11ea-9748-2759c758c984.png">

Is this consistent with what you would expect? However, when using in Emacs is get:

<img width="1278" alt="lsp_dual_proc_emacs_4tasks2" src="https://user-images.githubusercontent.com/27214625/80306965-9723a400-8809-11ea-8e3c-defaa20c2305.png">

And when disabling the `lsp-mode` (i.e., not using the `languageserver`) in Emacs I get: 

<img width="1278" alt="lsp_dual_proc_emacs_1tasks" src="https://user-images.githubusercontent.com/27214625/80306980-af93be80-8809-11ea-8523-a795083dc597.png">

So the fourth process is created when using `R` in Emacs with [`ess`](https://github.com/emacs-ess/ESS). Looking at the CPU differences between is pretty massive when not using `languageserver`…

@randy3k or @renkun-ken do you guys have any thoughts here? (Not sure if @yyoncho would have any input here on the `lsp-mode` side, or @jabranham on the `ess` side).

**Comment by renkun-ken** [comment] 2020-04-26 13:11
@atanasj Yes, it is consistent with what we know.

The master process runs `languageserver::run()`. When user types in the editor, the completion list is computed by the master process, but the typing modifies the document, causing documentDidChange, which triggers diagnostics process and parse process, when parse process completes, a dependency-resolving process starts and ends quickly.

In VSCode, the documentDidChange and completion request is not triggered on each key stroke but a number of key strokes in a span of time so that they are not triggered too frequently. But I guess in Emacs it seems that it triggers the documentDidChange and completion request too frequently so that the CPU usage looks higher. If they are triggered on each stroke, then it would be certainly too heavy for a 4-CPU machine.

**Comment by atanasj** [comment] 2020-04-26 14:30
Okay… Seems a similar issues was brought for another language (see [here](https://github.com/emacs-lsp/lsp-mode/issues/885#issuecomment-502202196)). 

Does `languageserver`  add debounce processing of didChange events? (Full disclosure, I don't know what this means).

**Comment by yyoncho** [comment] 2020-04-26 16:27
> In VSCode, the documentDidChange and completion request is not triggered on each key stroke but a number of key strokes in a span of time

This does not seem to be true - I opened random file managed by Java language server in vscode and I pressed a letter for 2-3 seconds and I saw ~100+ didChange notifications with single letter change. Up to my knowledge, batching should be performed on the server-side since it can smartly/better organize them. But in general, lsp-mode is a bit more aggressive with highlights, lenses and hover requests(and related) - this is controlled by lsp-idle-delay. Other than that, lsp-mode performs as much requests as vscode.

**Comment by renkun-ken** [comment] 2020-04-26 22:29
>This does not seem to be true - I opened random file managed by Java language server in vscode and I pressed a letter for 2-3 seconds and I saw ~100+ didChange notifications with single letter change.

Yes, you are right, sorry for my memory mixing up that the didChange occurs on each key stroke while the completion request does not in VSCode. You could turn on `r.lsp.debug` to see the language server logging, and you could clearly see when the lsp handlers are triggered. But the 100+ didChange notifications with single letter change looks odd to me, since R languageserver does not receive that many didChange but exactly one at a time.

Looks like we could do some server-side batch as you suggested so that unnecessary computing could be reduced.

**Comment by atanasj** [comment] 2020-04-26 22:39
Thanks @renkun-ken, would that batching be hard to implement? Also, can I set the `r.lsp.debug` variable outside `VSCode` i.e., to see what is happening within `Emacs`? Can I set it in my `.Rprofile` or somewhere else?

**Comment by renkun-ken** [comment] 2020-04-26 22:53
The batching should not be hard to implement. I'll think about it soon.

I have no clue how to set debug mode in Emacs. @randy3k any idea on this?

**Comment by randy3k** [comment] 2020-04-26 23:00
I am not sure what `batching` exactly refers to. But there is already a mechanism in place to reduce the number of executions: https://github.com/REditorSupport/languageserver/blob/adbe7be669b088dd5ec929e37fb448eb0691899c/R/task.R#L57-L57

The task manager wouldn't run any tasks if it has been invoked in the past 0.1 sec. We may want to decrease this value?

**Comment by atanasj** [comment] 2020-04-26 23:03
I don't know what to add here at all, but is `throttle` different to `debounce`? Is it answered [here](https://stackoverflow.com/a/61120437/8433651) or [here](https://css-tricks.com/the-difference-between-throttling-and-debouncing/). 

Also, and again I don't really know anything here, but it would be great to set a debug function from `Emacs`. I was thinking about setting an alias in my `.Rprofile` so it default to `debug = TRUE`... I found some ideas [here](https://www.r-bloggers.com/hijacking-r-functions-changing-default-arguments/).

**Comment by randy3k** [comment] 2020-04-26 23:10
They are a bit different, we definitely do not want to debounce our task manager. Otherwise, there is a high chance that it would not run any tasks.

**Comment by atanasj** [comment] 2020-04-26 23:14
Thanks @randy3k, I don't know anything about it at all, so I'll defer to you guys. I wasn't sure what was possible between different languages as @yyoncho says [here](https://github.com/emacs-lsp/lsp-mode/issues/885#issuecomment-502202196) that some languageservers use this method and I think `shiny` uses a debounce function, but again, not sure how this works and whether it would be applicable in this case.

I look forward to an update as having `languageserver` in `Emacs` running smoothly with `ess` and `R` would be awesome!!

**Comment by renkun-ken** [comment] 2020-04-26 23:19
@randy3k Yes, `throttle` certainly reduces some computing yet it seems a bit different from what I believe to be ideal where a series of didChange occurs and very close in time, only the last didChange should trigger child processes so that the results are sync with the latest document. 

Suppose user start typing after a number of idle seconds and input five characters quickly. `throttle` seems to work in a way that the first input triggers the tasks but all the rest do not (because the time difference with the last execution time is not big enough to create a task). Then the result is not sync with the latest document? I'm not sure if I miss something on this?

An ideal way is to let the last didChange create tasks instead of the first in a series. The only way I can come up with to do this is to wait so that if no task request occurs in e.g. 300ms, then run the last task request. But in R, it looks a bit tricky to wait without blocking the main thread, maybe we need something like `later`?

**Comment by atanasj** [comment] 2020-04-26 23:34
Thanks for your ongoing work on this guys. Just for the record, I think this is the variable to get the debug working `(setq lsp-clients-r-server-command '("R" "--slave" "-e" "languageserver::run(debug = TRUE)"))`, but not sure where it prints too. 

@yyoncho, where does the debug go to from the `R` `languageserver` process get printed to?

**Comment by randy3k** [comment] 2020-04-27 00:39
Just to explain it a bit clearer, under the current implementation, if five `didChange` occurs within 0.1 seconds. The first one is put in the queue and then be executed, the second one is then put in the queue. Then the third one is put in the queue and replaced the second one, the fourth replaces the third and the fifth replaces the forth. After 0.1 sec, the fifth will be executed.

**Comment by yyoncho** [comment] 2020-04-27 05:19
@atanasj 

> But not sure where it prints to. @yyoncho, where does the debug go to from the R languageserver process gets printed to?

It is hard to tell without knowing what the server does.

Did you had the chance to test after increasing lsp-idle-delay?

**Comment by atanasj** [comment] 2020-04-27 08:48
@yyoncho, I increased out to 1.0 with no perceptible difference. Should it go higher?

**Comment by renkun-ken** [comment] 2020-04-27 11:01
@randy3k I tried recording the time when task is added and then `run_tasks` only runs tasks added at least 0.5s ago and drops tasks whose life is less than 0.5s, and the CPU usage looks much better when I keep inputing characters in the editor and when the editing stops for 0.5s, the tasks start. Everything looks good under such mechanism. May I file an PR on this so that @atanasj could test?

**Comment by renkun-ken** [comment] 2020-04-27 14:01
@atanasj I made some changes to the current task manager and the CPU usage looks better for me now. Would you like to have a try with

```r
devtools::install_github("renkun-ken/languageserver@task-delay")
```

**Comment by atanasj** [comment] 2020-04-27 22:54
Thanks @renkun-ken, I have tested and seems to make little difference. I pushed out the the `idle-delay...` times as suggested by @yyoncho, but still no good. Having `languageserver` makes the experience of `R` in `Emacs` just that much better, however it is more or less unusable. :-( 

Any other options? Also, out of curiosity, how does `RStudio` implement their completion/helper feature?

**Comment by renkun-ken** [comment] 2020-04-27 23:30
@atanasj 

>how does RStudio implement their completion/helper feature?

To my knowledge, RStudio relies on the completion provided by a live R session and a limited number of code-based features. languageserver is purely static analysis and does not rely on live R session.

I guess running a master process of languageserver and occasionally two task processes in background, and also a user session doing the computing, is still too many for a 4-cpu machine.

I created an experimental branch at https://github.com/renkun-ken/languageserver/tree/low-cpu for you to try disabling run_linter and parse on didChange, and increase the `cpu_load` ratio and task `delay` to see if anything could be improved.

Would you like to have try with 

```r
devtools::install_github("renkun-ken/languageserver@low-cpu")
```

and add the following options to your `~/.Rprofile`. Test after restart the languageserver (e.g. reload window in vscode) whenever the `.Rprofile` is changed.

1. No lintr and parse on didChange: this should be no significant CPU usage when editing a document since no background process is created on didChange.

```r
options(
  languageserver.did_change.run_lintr = FALSE,
  languageserver.did_change.parse = FALSE,
  languageserver.task_manager.cpu_load = 0.5,
  languageserver.task_manager.delay = 0.5
)
```

2. Only parse, no lintr: only one background process is created on didChange with a document,  CPU usage should be low most of the time:

```r
options(
  languageserver.did_change.run_lintr = FALSE,
  languageserver.did_change.parse = TRUE,
  languageserver.task_manager.cpu_load = 0.5,
  languageserver.task_manager.delay = 1
)
```

For 4-cpu machine, I guess the way to make it useable is to only allow one background process in total, i.e. run parse -> resolve -> diagnostics in sequential order.

**Comment by atanasj** [comment] 2020-04-28 00:23
Thanks @renkun-ken, I'll give it a go. Should I still keep the below in my `.Rprofile`?

```r
## languageserver options recommended
options(
    languageserver.server_capabilities = list(
        documentOnTypeFormattingProvider = FALSE,
        documentLinkProvider = FALSE,
        colorProvider = FALSE
    )
)
```

**Comment by renkun-ken** [comment] 2020-04-28 00:25
@atanasj  You should remove those since it seems that they are not the main cause of high CPU usage.

**Comment by atanasj** [comment] 2020-04-28 00:46
Thanks. Okay, so I tried all combinations with and without the `languageserver.server_capabilities` options, and still no good. I am testing this in `Emacs`, as this is where I see the biggest performance hit. The CPU usage has gone down a bit, it is pretty quick to save, but the buffers still freezes and sputters when I type. 

I wonder if this is an `Emacs` issues, or my machine or something else. I don't have any other machine to test it on at the moment. @yyoncho do you have any thoughts about this?

Is there anyone else that could test this on `Emacs` or is there another solution?

**Comment by renkun-ken** [comment] 2020-04-28 01:07
Looks like you have both

```r
languageserver.did_change.run_lintr = FALSE
languageserver.did_change.parse = FALSE
```

and still have performance issue in Emacs, I guess that it's most likely an Emacs issue of how buffers are managed along with LSP operations.

**Comment by atanasj** [comment] 2020-04-28 02:33
That's a shame… I really like what LSP can do, but this makes it unusable in `Emacs`. It's not a total loss, `Emacs` and `ess` already had some very powerful completion built in via `company-mode`, however it just isn't as fancy as the LSP implementation.

I'll see if I can test on another machine, but otherwise what do you suggest?

**Comment by renkun-ken** [comment] 2020-04-28 03:38
Do you have access to a more powerful machine like 8+ cpus? If it still does not work smoothly with all features enabled, then I guess we can do nothing about it but hope for the improvement of Emacs lsp support.

**Comment by yyoncho** [comment] 2020-04-28 04:43
> @yyoncho do you have any thoughts about this?

IMO `lsp-mode` has a slightly different call pattern than vscode which undercovers server-side performance bug. E. g. you have enabled a different set of features like you have signatureHelp on lsp-mode side but you do not have that in vscode. One possible solution is:

1. Find out what is causing the language server performance issue. At this point, this is not clear.
2. Try fixing it on the server-side. 
3. If serverside is not capable of fixing their perf issue - workaround it on client-side by avoiding calling that method so much. On the lsp-mode side, you could change any behaviour your want.

1) could be achieved by comparing the traffic between lsp-mode and the server to the traffic between vscode and the server(which calls perform lsp-mode/vscode and how often).

**Comment by atanasj** [comment] 2020-04-28 11:41
Okay, so I tested on another machine, and performance was improved but was still bogged down. @renkun-ken, I think some of it may be machine. I was certain I had 4 cores, but the below says I don't… Here are my machine stats:

```bash
ProductName:    Mac OS X
ProductVersion: 10.14.6
BuildVersion:   18G3020
Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro11,1
      Processor Name: Intel Core i7
      Processor Speed: 2.8 GHz
      Number of Processors: 1
      Total Number of Cores: 2
      L2 Cache (per Core): 256 KB
      L3 Cache: 4 MB
      Hyper-Threading Technology: Enabled
      Memory: 16 GB
```

Here is the stats of the other machine: 

```bash
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G3020

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro13,3
      Processor Name: Intel Core i7
      Processor Speed: 2.6 GHz
      Number of Processors: 1
      Total Number of Cores: 4
      L2 Cache (per Core): 256 KB
      L3 Cache: 6 MB
      Hyper-Threading Technology: Enabled
      Memory: 16 GB
```

Same version of `Emacs`, `R` and all associated packages. I tried your recommendations and experimental version of `languageserver` again, performance did improve slightly but not that much. When compared to how `languageserver` performs in `VSCode`, it is not really usable in `Emacs`. @renkun-ken, are @yyoncho's suggestions possible? Is this something I have to do? Is it actually of any use, as I may be the only one that seems to have an issue…

Thoughts?

**Comment by renkun-ken** [comment] 2020-04-28 11:46
@atanasj Maybe you could post the output of

```r
parallel::detectCores()
```

on both machines.

**Comment by yyoncho** [comment] 2020-04-28 11:54
@atanasj can you clarify what is slow in your setup? Emacs or the server itself? If client side feels slow, there is a guide on lsp-mode's readme about the performance troubleshooting. If the server is slow, as I mentioned in my previous post I recommend trying to collect the calls performed by both lsp-mode and vscode and compare them. Set lsp-print-io to t and then use lsp-workspace-show-log to get the actual log(note that enabling the logs will slow down emacs a lot).

**Comment by atanasj** [comment] 2020-04-28 11:56
Mine:

```r
> parallel::detectCores()
[1] 4
```

Other:

```r
> parallel::detectCores()
[1] 8
```

**Comment by atanasj** [comment] 2020-04-28 12:05
@yyoncho, the server feels slow. `Emacs` is fast when not using `languageserver`. When I use plain `ess` with `company-mode` it is fast.

**Comment by yyoncho** [comment] 2020-04-28 12:09
@atanasj if emacs is not responsive, e. g. it does not respond while typing, deleting, etc. it is client side problem. If for example, the completion is slow and appears after a lot time but you could type without issues, then the perf issue is most likely on the server.

**Comment by atanasj** [comment] 2020-04-28 12:27
@yyoncho, do you mean with `lsp` enabled? What happens is `Emacs` is that it seems to freeze whilst typing, but then the keystrokes are executed after some time. This has certainly improved with the changes made and recommended by @renkun-ken, but still there.

**Comment by yyoncho** [comment] 2020-04-28 12:29
@atanasj if emacs is freezing this means that something is misconfigured on lsp-mode's side, please follow up this guide - https://github.com/emacs-lsp/lsp-mode#reporting-performance-problems .

**Closed** 2020-04-30 14:38 UTC
