### ISSUE TITLE
"No newline at end of file" after formatting file in VS Code

### ISSUE THREAD

**Issue by bersbersbers** [REditorSupport/languageserver#462] opened 2021-08-05 07:37 UTC
1. Create a file `bug.R` containting this line: `styler::style_file("bug.R")` (no newline at end of file).
2. Run it using `Rscript bug.R`
3. Note that a newline at the end of file has been introduced. So this seems to be tidyverse style.
4. Note also that the GitHub web-interface file editor introduces a newline at the end of the file - there is no way to even avoid it.
5. `.Rprofile` ignores the last line if it does not end in a newline, see https://yihui.org/en/2018/04/rprofile-trailing-newline/

I think the above establishes that a file should end in a newline character.

Now, the R language server seems to remove that newline character - inconsistently!

![hTLPI9Kei2](https://user-images.githubusercontent.com/12128514/128310564-bc9395f1-50af-4e6c-abb4-b235ee6c1d1f.gif)

Note especially how with `"editor.formatOnSave": true`, it takes me 5 tries to reproduce the problem.

**Comment by renkun-ken** [comment] 2021-08-05 09:57
You might want to turn on `files.insertFinalNewline` in your vscode settings as a quick walk-around.

I'll take a closer look at the document formatting provider then.

**Comment by bersbersbers** [comment] 2021-08-05 10:59
Thanks for looking into this! Just know that `files.insertFinalNewline` inserts an additional newline, which results in a duplicate newline in those cases where the trailing newline was not removed originally. So you either have 0 or 1 newline, OR 1 or 2 newlines - never 1 newline consistently.

**Comment by lorenzwalthert** [comment] 2021-08-09 09:29
FWIW: The reason why styler ensures always exactly one trailing empty line (when the I put is a file, eg not in `style_text()`) is described here: https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file

**Comment by lorenzwalthert** [comment] 2021-08-09 20:51
Other people have experienced this while formatting on save: https://github.com/apache/arrow/pull/10879#issuecomment-895293565

**Comment by lorenzwalthert** [comment] 2021-12-27 21:21
This seems to be a major headache for some people. Can we fix it?

**Comment by renkun-ken** [comment] 2021-12-28 01:31
Let me take a look into this.

**Comment by renkun-ken** [comment] 2021-12-28 10:16
Looks like it i caused by the how styler use cache and how it handles empty line.

First, clear the styler cache.

```shell
rm -rf ~/.cache/R/R.cache/styler
```

Then try the following:

```r
> str(styler::style_text(c("print(1)", "")))                                                                        
 'vertical' chr "print(1)"

> str(styler::style_text(c("print(1)", "")))                                                                        
 'vertical' chr [1:2] "print(1)" ""

> str(styler::style_text(c("print(1)", "")))                                                                        
 'vertical' chr [1:2] "print(1)" ""

> str(styler::style_text(c("print(2)", "")))                                                                        
 'vertical' chr "print(2)"

> str(styler::style_text(c("print(2)", "")))                                                                        
 'vertical' chr [1:2] "print(2)" ""

> str(styler::style_text(c("print(2)", "")))                                                                        
 'vertical' chr [1:2] "print(2)" ""

> str(styler::style_text(c("print(3)", "")))                                                                        
 'vertical' chr "print(3)"

> str(styler::style_text(c("print(3)", "")))                                                                        
 'vertical' chr [1:2] "print(3)" ""

> str(styler::style_text(c("print(3)", "")))                                                                        
 'vertical' chr [1:2] "print(3)" ""
```

Looks like it should be fixed in styler where inconsistent results are returned? @lorenzwalthert

**Comment by lorenzwalthert** [comment] 2021-12-28 10:18
Ugh, you are right @renkun-ken. Thanks for looking into it. I will have a look.

**Comment by lorenzwalthert** [comment] 2021-12-28 13:31
Seems like it's fixed in dev version of {styler}. Should we just ask people to install the dev version of {styler} or do we need a fix here too? You could check for `packageVersion('styler') < '1.6.2.9000` and if that's true, `styler:::ensure_last_n_empty(styled_code, n = 1)` (or n = 0, not sure how to make sure there is exactly one trailing newline after the formatting is completed). That function exists [since {styler} 1.3.2](https://github.com/r-lib/styler/blob/01a935d0d28121686e04a69fb4a034030c9bc157/R/utils.R) (released over two years ago).

**Comment by lorenzwalthert** [comment] 2021-12-28 13:32
In any case, I think once I release a {styler} update, there should be a minimal version requirement for {styler}.

**Comment by renkun-ken** [comment] 2021-12-28 15:19
@lorenzwalthert Do you think #509 should work with both CRAN release and latest dev of styler?

@bersbersbers Does #509 work for you?

**Closed** 2021-12-29 00:46 UTC

**Comment by lorenzwalthert** [comment] 2021-12-29 12:18
@nealrichardson @assignuser, with dev styler and dev languageserver, formatting should now be more consistent with regard to trailing blank line. Let us know if it works now for you.

**Comment by nealrichardson** [comment] 2021-12-29 16:38
@lorenzwalthert seems to be working for me now--thanks a lot!

**Comment by assignUser** [comment] 2022-01-05 17:56
Yep perfect, thanks!

**Comment by 888Greys** [comment] 2024-05-07 18:27
Thanks a lot. It worked
