### ISSUE TITLE
Bug when hovering variables

### ISSUE THREAD

**Issue by xiajunwen1007** [REditorSupport/languageserver#463] opened 2021-08-05 14:56 UTC
**Describe the bug**
When hover on a variable defined before, it shows the definition of the variable. But in some cases, definition isn't correct. For example, paste the following code in the vscode.
```
for (ll in 1:3){
 p = ll
 I = array(0:0, dim=c(p,p))
}
```
Then hover on the variable `p`. The correct behavior should be popping up a panel showing `p=ll`, but it shows `for (ll in 1:3){`. A screenshot is below.

![image](https://user-images.githubusercontent.com/49160447/128373518-5a908b71-783a-4e1c-8763-d472c3fb0068.png)

**Comment by renkun-ken** [comment] 2021-08-05 16:32
If the code is modified as below with `<-` as assignment, then the hover of `p` works as expected.

```r
for (ll in 1:3){
 p <- ll
 I = array(0:0, dim=c(p,p))
}
```

But `=` does not work correctly in this case. Let me take a closer look at this.

**Comment by renkun-ken** [comment] 2021-08-05 16:41
The following case works as expected.

```r
local({
  for (ll in 1:3) {
    p1 = ll
    I = array(0:0, dim = c(p1, p1))
  }
})
```

Then is must be caused by the competing workspace and scope definitions. In this case, the scope definition takes priority over the workspace definition but vice verse in the first example.

**Comment by renkun-ken** [comment] 2021-08-05 16:43
In this example, `p` does not work while `p1` works.

```r
for (ll in 1:3) {
  p = ll
  p1 = ll
  I = array(0:0, dim = c(p, p1))
}
```

**Comment by renkun-ken** [comment] 2021-08-05 16:50
If you move your cursor on the right side of `p`, then it works too.

<img width="366" alt="image" src="https://user-images.githubusercontent.com/4662568/128389326-8a036868-3287-45df-871c-4a7a7809f689.png">

Not sure why hovering on the left half of `p` shows the `for (ll in 1:3) {`.

**Comment by xiajunwen1007** [comment] 2021-08-06 00:10
> If the code is modified as below with `<-` as assignment, then the hover of `p` works as expected.

`<-` doesn't work as well. When I first hover on the left half of the `p` variable in the `c(p,p)`, it shows correct definition. Things go wrong after first hovering.

![屏幕录制2021-08-06 上午8 05 35](https://user-images.githubusercontent.com/49160447/128436750-9bcd59d9-f368-44cd-907a-5a2153165651.gif)

**Comment by renkun-ken** [comment] 2021-08-06 13:12
Should be fixed via #464. Would you like you try and see if it works for you?

**Comment by renkun-ken** [comment] 2021-08-06 13:33
You could use the following to try:

```r
remotes::install_github("REditorSupport/languageserver#463")
```

**Comment by xiajunwen1007** [comment] 2021-08-06 15:04
I tried this, it seems there are still some problems. Maybe I configure something wrong. I posted a screenshot blew.
![image](https://user-images.githubusercontent.com/49160447/128530506-c4ad6f74-e725-48bb-800a-9d98455c4644.png)
Sometimes it will pop up definition, and sometimes not.

**Comment by renkun-ken** [comment] 2021-08-06 15:08
The hover extracts the word when you move your cursor on the right part of the word. The help links are generated by vscode-R which uses the editor api to get the word under cursor. They are two different sources of hover information.

**Comment by xiajunwen1007** [comment] 2021-08-06 16:15
Thank you very much. Now everything works fine. I also found the format would affect the hovering behavior. For example, I extract a part of my teacher's code. The format is ugly.
```
for (l in 1:rep){
b1=array(0:0,dim=c(p,K))
index1 = sample(rep(1:p))[1:sp]

for (d in 1:K){
	for (i in index1){b1[i,d]=(1+runif(1))*sqrt(log(p)/n1)*sample(c(1,-1),1)}
}
```
Things go wrong when I hover on `index1`. 
![image](https://user-images.githubusercontent.com/49160447/128540217-9a9a86e6-fcfb-4bfe-8018-3ed1f8b230da.png)

It works when the format is good though the code is the same.
```
for (l in 1:rep) {
 b1 <- array(0:0, dim = c(p, K))
 index1 <- sample(rep(1:p))[1:sp]

 for (d in 1:K) {
  for (i in index1) {
   b1[i, d] <- (1 + runif(1)) * sqrt(log(p) / n1) * sample(c(1, -1), 1)
  }
 }
}
```
![image](https://user-images.githubusercontent.com/49160447/128540472-77d2fa2c-2869-4714-8039-ec4dab4a9bf0.png)

Nonetheless, it's enough for me. Thank you very much.

**Comment by renkun-ken** [comment] 2021-08-06 16:37
> Thank you very much. Now everything works fine. I also found the format would affect the hovering behavior. For example, I extract a part of my teacher's code. The format is ugly.

This is quite interesting. Didn't expect such difference before. I'll take a closer look soon.

**Comment by renkun-ken** [comment] 2021-08-06 22:34
Looks like there is a gap between the col1, col2 from `getParseData()` and the actual col1, col2 from the editor content.

```r
> getParseData(e)                                                                                             
    line1 col1 line2 col2  id parent                  token terminal   text
246     1    1     8    1 246      0                   expr    FALSE       
1       1    1     1    3   1    246                    FOR     TRUE    for
13      1    5     1   16  13    246                forcond    FALSE       
2       1    5     1    5   2     13                    '('     TRUE      (
3       1    6     1    6   3     13                 SYMBOL     TRUE      l
4       1    8     1    9   4     13                     IN     TRUE     in
11      1   11     1   15  11     13                   expr    FALSE       
5       1   11     1   11   5      6              NUM_CONST     TRUE      1
6       1   11     1   11   6     11                   expr    FALSE       
7       1   12     1   12   7     11                    ':'     TRUE      :
8       1   13     1   15   8     10                 SYMBOL     TRUE    rep
10      1   13     1   15  10     11                   expr    FALSE       
9       1   16     1   16   9     13                    ')'     TRUE      )
243     1   17     8    1 243    246                   expr    FALSE       
14      1   17     1   17  14    243                    '{'     TRUE      {
58      2    1     2   24  58    243 expr_or_assign_or_help    FALSE       
16      2    1     2    2  16     18                 SYMBOL     TRUE     b1
18      2    1     2    2  18     58                   expr    FALSE       
17      2    3     2    3  17     58              EQ_ASSIGN     TRUE      =
55      2    4     2   24  55     58                   expr    FALSE       
20      2    4     2    8  20     22   SYMBOL_FUNCTION_CALL     TRUE  array
22      2    4     2    8  22     55                   expr    FALSE       
21      2    9     2    9  21     55                    '('     TRUE      (
29      2   10     2   12  29     55                   expr    FALSE       
23      2   10     2   10  23     24              NUM_CONST     TRUE      0
24      2   10     2   10  24     29                   expr    FALSE       
25      2   11     2   11  25     29                    ':'     TRUE      :
26      2   12     2   12  26     27              NUM_CONST     TRUE      0
27      2   12     2   12  27     29                   expr    FALSE       
28      2   13     2   13  28     55                    ','     TRUE      ,
33      2   14     2   16  33     55             SYMBOL_SUB     TRUE    dim
34      2   17     2   17  34     55                 EQ_SUB     TRUE      =
50      2   18     2   23  50     55                   expr    FALSE       
35      2   18     2   18  35     37   SYMBOL_FUNCTION_CALL     TRUE      c
37      2   18     2   18  37     50                   expr    FALSE       
36      2   19     2   19  36     50                    '('     TRUE      (
38      2   20     2   20  38     40                 SYMBOL     TRUE      p
40      2   20     2   20  40     50                   expr    FALSE       
39      2   21     2   21  39     50                    ','     TRUE      ,
44      2   22     2   22  44     46                 SYMBOL     TRUE      K
46      2   22     2   22  46     50                   expr    FALSE       
45      2   23     2   23  45     50                    ')'     TRUE      )
51      2   24     2   24  51     55                    ')'     TRUE      )
100     3    1     3   31 100    243 expr_or_assign_or_help    FALSE       
60      3    1     3    6  60     62                 SYMBOL     TRUE index1
62      3    1     3    6  62    100                   expr    FALSE       
61      3    8     3    8  61    100              EQ_ASSIGN     TRUE      =
97      3   10     3   31  97    100                   expr    FALSE       
85      3   10     3   25  85     97                   expr    FALSE       
64      3   10     3   15  64     66   SYMBOL_FUNCTION_CALL     TRUE sample
66      3   10     3   15  66     85                   expr    FALSE       
65      3   16     3   16  65     85                    '('     TRUE      (
80      3   17     3   24  80     85                   expr    FALSE       
67      3   17     3   19  67     69   SYMBOL_FUNCTION_CALL     TRUE    rep
69      3   17     3   19  69     80                   expr    FALSE       
68      3   20     3   20  68     80                    '('     TRUE      (
76      3   21     3   23  76     80                   expr    FALSE       
70      3   21     3   21  70     71              NUM_CONST     TRUE      1
71      3   21     3   21  71     76                   expr    FALSE       
72      3   22     3   22  72     76                    ':'     TRUE      :
73      3   23     3   23  73     75                 SYMBOL     TRUE      p
75      3   23     3   23  75     76                   expr    FALSE       
74      3   24     3   24  74     80                    ')'     TRUE      )
81      3   25     3   25  81     85                    ')'     TRUE      )
86      3   26     3   26  86     97                    '['     TRUE      [
93      3   27     3   30  93     97                   expr    FALSE       
87      3   27     3   27  87     88              NUM_CONST     TRUE      1
88      3   27     3   27  88     93                   expr    FALSE       
89      3   28     3   28  89     93                    ':'     TRUE      :
90      3   29     3   30  90     92                 SYMBOL     TRUE     sp
92      3   29     3   30  92     93                   expr    FALSE       
91      3   31     3   31  91     97                    ']'     TRUE      ]
238     5    1     7    1 238    243                   expr    FALSE       
104     5    1     5    3 104    238                    FOR     TRUE    for
116     5    5     5   14 116    238                forcond    FALSE       
105     5    5     5    5 105    116                    '('     TRUE      (
106     5    6     5    6 106    116                 SYMBOL     TRUE      d
107     5    8     5    9 107    116                     IN     TRUE     in
114     5   11     5   13 114    116                   expr    FALSE       
108     5   11     5   11 108    109              NUM_CONST     TRUE      1
109     5   11     5   11 109    114                   expr    FALSE       
110     5   12     5   12 110    114                    ':'     TRUE      :
111     5   13     5   13 111    113                 SYMBOL     TRUE      K
113     5   13     5   13 113    114                   expr    FALSE       
112     5   14     5   14 112    116                    ')'     TRUE      )
235     5   15     7    1 235    238                   expr    FALSE       
117     5   15     5   15 117    235                    '{'     TRUE      {
230     6    9     6   81 230    235                   expr    FALSE       
119     6    9     6   11 119    230                    FOR     TRUE    for
127     6   13     6   25 127    230                forcond    FALSE       
120     6   13     6   13 120    127                    '('     TRUE      (
121     6   14     6   14 121    127                 SYMBOL     TRUE      i
122     6   16     6   17 122    127                     IN     TRUE     in
123     6   19     6   24 123    125                 SYMBOL     TRUE index1 <<<<<<<<<<<
125     6   19     6   24 125    127                   expr    FALSE       
124     6   25     6   25 124    127                    ')'     TRUE      )
227     6   26     6   81 227    230                   expr    FALSE       
128     6   26     6   26 128    227                    '{'     TRUE      {
225     6   27     6   80 225    227 expr_or_assign_or_help    FALSE       
144     6   27     6   33 144    225                   expr    FALSE       
129     6   27     6   28 129    131                 SYMBOL     TRUE     b1
131     6   27     6   28 131    144                   expr    FALSE       
130     6   29     6   29 130    144                    '['     TRUE      [
132     6   30     6   30 132    134                 SYMBOL     TRUE      i
134     6   30     6   30 134    144                   expr    FALSE       
133     6   31     6   31 133    144                    ','     TRUE      ,
138     6   32     6   32 138    140                 SYMBOL     TRUE      d
140     6   32     6   32 140    144                   expr    FALSE       
139     6   33     6   33 139    144                    ']'     TRUE      ]
145     6   34     6   34 145    225              EQ_ASSIGN     TRUE      =
223     6   35     6   80 223    225                   expr    FALSE       
189     6   35     6   62 189    223                   expr    FALSE       
164     6   35     6   46 164    189                   expr    FALSE       
147     6   35     6   35 147    164                    '('     TRUE      (
162     6   36     6   45 162    164                   expr    FALSE       
148     6   36     6   36 148    149              NUM_CONST     TRUE      1
149     6   36     6   36 149    162                   expr    FALSE       
150     6   37     6   37 150    162                    '+'     TRUE      +
160     6   38     6   45 160    162                   expr    FALSE       
151     6   38     6   42 151    153   SYMBOL_FUNCTION_CALL     TRUE  runif
153     6   38     6   42 153    160                   expr    FALSE       
152     6   43     6   43 152    160                    '('     TRUE      (
154     6   44     6   44 154    155              NUM_CONST     TRUE      1
155     6   44     6   44 155    160                   expr    FALSE       
156     6   45     6   45 156    160                    ')'     TRUE      )
161     6   46     6   46 161    164                    ')'     TRUE      )
165     6   47     6   47 165    189                    '*'     TRUE      *
187     6   48     6   62 187    189                   expr    FALSE       
166     6   48     6   51 166    168   SYMBOL_FUNCTION_CALL     TRUE   sqrt
168     6   48     6   51 168    187                   expr    FALSE       
167     6   52     6   52 167    187                    '('     TRUE      (
183     6   53     6   61 183    187                   expr    FALSE       
178     6   53     6   58 178    183                   expr    FALSE       
169     6   53     6   55 169    171   SYMBOL_FUNCTION_CALL     TRUE    log
171     6   53     6   55 171    178                   expr    FALSE       
170     6   56     6   56 170    178                    '('     TRUE      (
172     6   57     6   57 172    174                 SYMBOL     TRUE      p
174     6   57     6   57 174    178                   expr    FALSE       
173     6   58     6   58 173    178                    ')'     TRUE      )
179     6   59     6   59 179    183                    '/'     TRUE      /
180     6   60     6   61 180    182                 SYMBOL     TRUE     n1
182     6   60     6   61 182    183                   expr    FALSE       
181     6   62     6   62 181    187                    ')'     TRUE      )
188     6   63     6   63 188    223                    '*'     TRUE      *
221     6   64     6   80 221    223                   expr    FALSE       
190     6   64     6   69 190    192   SYMBOL_FUNCTION_CALL     TRUE sample
192     6   64     6   69 192    221                   expr    FALSE       
191     6   70     6   70 191    221                    '('     TRUE      (
210     6   71     6   77 210    221                   expr    FALSE       
193     6   71     6   71 193    195   SYMBOL_FUNCTION_CALL     TRUE      c
195     6   71     6   71 195    210                   expr    FALSE       
194     6   72     6   72 194    210                    '('     TRUE      (
196     6   73     6   73 196    197              NUM_CONST     TRUE      1
197     6   73     6   73 197    210                   expr    FALSE       
198     6   74     6   74 198    210                    ','     TRUE      ,
206     6   75     6   76 206    210                   expr    FALSE       
202     6   75     6   75 202    206                    '-'     TRUE      -
203     6   76     6   76 203    204              NUM_CONST     TRUE      1
204     6   76     6   76 204    206                   expr    FALSE       
205     6   77     6   77 205    210                    ')'     TRUE      )
211     6   78     6   78 211    221                    ','     TRUE      ,
215     6   79     6   79 215    216              NUM_CONST     TRUE      1
216     6   79     6   79 216    221                   expr    FALSE       
217     6   80     6   80 217    221                    ')'     TRUE      )
222     6   81     6   81 222    227                    '}'     TRUE      }
233     7    1     7    1 233    235                    '}'     TRUE      }
241     8    1     8    1 241    243                    '}'     TRUE      }
```

**Comment by renkun-ken** [comment] 2021-08-06 22:39
I think I found the problem here. You use a tab instead of spaces before `for (i in index1)` where the tab takes two text columns in the editor. A minimal example is

```r
index1 <- 1
{
	index1 + 1
}
```

**Comment by renkun-ken** [comment] 2021-08-06 22:50
@randy3k Do you think we could/should fix this on our side? Maybe we could fix this via improving `code_point_from_unit` and `code_point_to_unit` by taking `\t` into account, but this also relies on the document settings for the number of spaces of tab?

**Comment by renkun-ken** [comment] 2021-08-06 23:03
Looks like the LSP takes `\t` as one column character. Therefore, we could simply replace `\t` with a space in `parse_document`. I tried it and it works nicely now.

**Comment by randy3k** [comment] 2021-08-06 23:17
> Looks like the LSP takes `\t` as one column character. Therefore, we could simply replace `\t` with a space in `parse_document`. I tried it and it works nicely now.

The tab thing seems to have broader implications. It also affects tabs in strings.

```
sf <- srcfile("txt")
parse(text = "'\t'", srcfile = sf)
getParseData(sf)
#>   line1 col1 line2 col2 id parent     token terminal text
#> 1     1    1     1    9  1      3 STR_CONST     TRUE '\t'
#> 3     1    1     1    9  3      0      expr    FALSE
```

I think replacing them with spaces in `parse_document` is a reasonable workaround though.

**Comment by renkun-ken** [comment] 2021-08-07 02:29
@xiajunwen1007 You might want to try again the installation as it also fixes the tab issue.

**Comment by xiajunwen1007** [comment] 2021-08-07 04:16
Thank you, it is fixed now. However, I find a new bug related to the behavior of hovering from my teacher's code again. When there are symbol **;** behind the line, hovering panel works wrong. You can try the code below:
```
for (ll in 1:3){
 p=ll
 I = array(0:0, dim=c(p,p))
 k = 1;
}
```
Or

```
for (ll in 1:3){
 p=ll
 k = 1;
 I = array(0:0, dim=c(p,p))
}
```

Whether the symbol **;** is between `c(p,p)` and the definition of `p` or behind `c(p,p)`, the bug occurs. When the symbol **;** is before the definition of 'p', then there is no bug. The code is like this. 

```
for (ll in 1:3){
 k = 1;
 p=ll
 I = array(0:0, dim=c(p,p))
}
```

The following screenshot represents three code block before.

![image](https://user-images.githubusercontent.com/49160447/128587443-c987f393-a618-48b9-8656-aef820217caf.png)

![image](https://user-images.githubusercontent.com/49160447/128587477-5fb789c7-5621-4965-b37b-caf211717c69.png)

![image](https://user-images.githubusercontent.com/49160447/128587555-070fc204-5703-4587-8e12-1c980ea9343f.png)

As I know, there is no need to write ; after the line. So it's OK to ignore this bug for me.

**Comment by renkun-ken** [comment] 2021-08-07 07:31
Just notice that `;` will produce a `exprlist` in the XML parse data. Let me fix this in those XPath-based providers.

**Comment by renkun-ken** [comment] 2021-08-07 09:41
@xiajunwen1007 Should be fixed now. You might want to have a try installing again.

**Comment by xiajunwen1007** [comment] 2021-08-07 09:59
Thank you a lot. Finally, everything is right.

**Closed** 2021-08-09 17:05 UTC
Labels: bug
