### ISSUE TITLE
unexpected '/' in R and linters disappear in Rmd

### ISSUE THREAD

**Issue by ErickChacon** [REditorSupport/languageserver#250] opened 2020-05-11 20:08 UTC
I am using `languageserver` with `LanguageClient-neovim`.  It works well but there are two issues after saving the file:

- There is an error at the top at the file with the message `unexpected '/'` when working in an `R` script.
- Linters disappear when working in an `Rmd` script.

I have temporarily solved both issues by installing version `0.3.4`. 

My `LanguageClient-neovim` config looks like:
```vim
let g:LanguageClient_serverCommands = {
    \ 'r': ['R', '--quiet', '--slave', '-e', 'languageserver::run()'],
    \ 'rmd': ['R', '--quiet', '--slave', '-e', 'languageserver::run()'],
    \ }

let g:LanguageClient_autoStart = 0
```

This happens even with a minimal `R` script.
```r

x <- 1:10
plot(x)
```

**Comment by randy3k** [comment] 2020-05-11 20:20
I am on the master branch and couldn't reproduce your issues.

<img width="650" alt="Screen Shot 2020-05-11 at 1 18 32 PM" src="https://user-images.githubusercontent.com/1690993/81607703-f47f2f80-9389-11ea-879d-53f30804169e.png">

<img width="650" alt="Screen Shot 2020-05-11 at 1 20 11 PM" src="https://user-images.githubusercontent.com/1690993/81607833-2b554580-938a-11ea-9bef-d688ea6da070.png">

Could you install the master branch and try again?

**Comment by randy3k** [comment] 2020-05-11 20:22
```
let g:LanguageClient_loggingFile = expand('/tmp/LanguageClient.log')
let g:LanguageClient_loggingLevel = 'DEBUG'
let g:LanguageClient_serverCommands.r = ['R', '--quiet', '--slave', '-e', 'languageserver::run(debug = TRUE)']
```
If possible, could you report the debug log `LanguageClient.log` as indicated above?

**Comment by ErickChacon** [comment] 2020-05-11 20:56
Here is the file:
[LanguageClient.log](https://github.com/REditorSupport/languageserver/files/4612021/LanguageClient.log)

**Comment by ErickChacon** [comment] 2020-05-11 21:07
Here is an screenshoot. Please, take into consideration that the error shows up when you save the file.
![langserver](https://user-images.githubusercontent.com/7862458/81611712-72b3f400-93d3-11ea-94d5-6a83dad93da0.png)

**Comment by jan-xyz** [comment] 2020-08-25 21:11
This seems to be fixed on master, can we get a new bugfix release with this soon?

**Comment by renkun-ken** [comment] 2020-10-29 15:48
Closing as fixed.

**Closed by renkun-ken** 2020-10-29 15:48 UTC
